# Generated by Django 2.2.2 on 2019-06-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('id_user', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_process', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status_phase', models.CharField(blank=True, max_length=15, null=True)),
                ('tasks_list', models.CharField(blank=True, max_length=200, null=True)),
                ('documents_list', models.CharField(blank=True, max_length=200, null=True)),
                ('final_report_doc', models.CharField(blank=True, max_length=200, null=True)),
                ('continues_doc', models.CharField(blank=True, max_length=200, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('id_user', models.CharField(blank=True, max_length=50, null=True)),
                ('user_list', models.CharField(blank=True, max_length=200, null=True)),
                ('documents_list', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
