# Generated by Django 2.2.2 on 2019-07-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_process',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
