# Generated by Django 2.2.2 on 2019-07-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0009_process_status_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='status_criteria',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='status_indicator',
        ),
        migrations.RemoveField(
            model_name='process',
            name='status_phase',
        ),
        migrations.AddField(
            model_name='process',
            name='status_process',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='status_phase',
            field=models.CharField(blank=True, default='0', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status_task',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
